name: Build Recovery By YudhoPRJKT

on:
  workflow_dispatch:
    inputs:
      RECOVERY:
        description: 'Choice '
        type: choice
        options:
          - test
          - tes123

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Handle Choice
        run: |
          case "${{ github.event.inputs.RECOVERY }}" in
            "test")
              echo "ini dari test input"
              ;;
            "tes123")
              echo "ini dari tes123 input"
              ;;
            *)
              echo "gagal"
              ;;
          esac
