name: Build Recovery By YudhoPRJKT

on:
  workflow_dispatch:
    inputs:
      RECOVERY:
        description: 'Choose Your Custom Recovery'
        type: choice
        options:
          - test
          - tes123
          - hai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Files
        run: |
          ls
      - name: Run1
        run: | 
          chmod 777 msg.sh
          sudo bash msg.sh
      
      - name: Handle Choice
        run: |
          case "${{ github.event.inputs.RECOVERY }}" in
            "test")
              echo "ini dari test input"
              ;;
            "tes123")
              echo "ini dari tes123 input"
              ;;
            "hai")
              echo "ini dari hai input"
              ;;
            *)
              echo "gagal"
              ;;
          esac
