name: Build 

on:
  workflow_dispatch:
    inputs:
      RECOVERY:
        description: 'Select the custom recovery you want '
        type: choice
        options:
          - test
          - tes123

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: as
        run: |
          if [ "${{ github.event.inputs.RECOVERY }}" == "test" ]; then
            echo "ini dari test input"

          else
            echo "gagal"
          fi

          if [ "${{ github.event.inputs.RECOVERY }}" == "tes123" ]; then
            echo "ini dari test input"
            
          else
            echo "gagal"
          fi


